apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::250446554271:user/github-cl
      username: github-cl
      groups:
        - system:masters
